-- 03_queries.sql — Competitive analysis queries for HabitONE
-- All queries are standalone and can be run in any order.
-- Assumes db/competitors.db was generated by 02_load_db.py.


-- Q1: Average price per gram by brand (full listed price, no discount applied)
SELECT
    b.name                                        AS brand,
    ROUND(AVG(p.price_usd / p.volume_g), 4)      AS avg_price_per_g,
    COUNT(*)                                       AS sku_count
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
GROUP BY b.name
ORDER BY avg_price_per_g;


-- Q2: Effective price per gram after applying discounts
SELECT
    b.name                                                                      AS brand,
    ROUND(AVG(p.price_usd * (1 - p.discount_pct / 100.0) / p.volume_g), 4)   AS effective_price_per_g
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
GROUP BY b.name
ORDER BY effective_price_per_g;


-- Q3: Where does HabitONE sit in the market price distribution?
WITH brand_avg AS (
    SELECT
        b.name,
        b.is_habitone,
        AVG(p.price_usd / p.volume_g) AS avg_ppg
    FROM prices p
    JOIN products pr ON pr.id = p.product_id
    JOIN brands b    ON b.id  = pr.brand_id
    WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
    GROUP BY b.name, b.is_habitone
),
ranked AS (
    SELECT
        name,
        is_habitone,
        ROUND(avg_ppg, 4) AS avg_ppg,
        ROUND(
            100.0 * (ROW_NUMBER() OVER (ORDER BY avg_ppg) - 1)
            / (COUNT(*) OVER () - 1),
            1
        ) AS pct_rank
    FROM brand_avg
)
SELECT * FROM ranked ORDER BY avg_ppg;


-- Q4: Share of SKUs with active discounts per brand
SELECT
    b.name                                                                                      AS brand,
    COUNT(*)                                                                                    AS total_skus,
    SUM(CASE WHEN p.discount_pct > 0 THEN 1 ELSE 0 END)                                        AS discounted_skus,
    ROUND(100.0 * SUM(CASE WHEN p.discount_pct > 0 THEN 1 ELSE 0 END) / COUNT(*), 1)           AS discount_coverage_pct
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
GROUP BY b.name
ORDER BY discount_coverage_pct DESC;


-- Q5: SKU count by brand and format — shows catalog depth and gaps
SELECT
    b.name       AS brand,
    pr.format,
    COUNT(*)     AS sku_count
FROM products pr
JOIN brands b ON b.id = pr.brand_id
GROUP BY b.name, pr.format
ORDER BY b.name, sku_count DESC;


-- Q6: Formats competitors offer that HabitONE does not
SELECT DISTINCT pr.format
FROM products pr
JOIN brands b ON b.id = pr.brand_id
WHERE b.is_habitone = 0
  AND pr.format NOT IN (
      SELECT DISTINCT pr2.format
      FROM products pr2
      JOIN brands b2 ON b2.id = pr2.brand_id
      WHERE b2.is_habitone = 1
  )
  AND pr.format IS NOT NULL
ORDER BY pr.format;


-- Q7: Average serving price by brand (broader coverage than price/g — 823 vs 583 rows)
SELECT
    b.name                                    AS brand,
    ROUND(AVG(p.serving_price), 3)            AS avg_serving_price,
    COUNT(*)                                  AS n
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
WHERE p.serving_price IS NOT NULL
GROUP BY b.name
ORDER BY avg_serving_price;


-- Q8: Amazon vs own_site average price gap per brand
SELECT
    b.name                                                                          AS brand,
    ROUND(AVG(CASE WHEN p.channel = 'own_site'  THEN p.price_usd END), 2)         AS own_site_avg,
    ROUND(AVG(CASE WHEN p.channel = 'amazon'    THEN p.price_usd END), 2)         AS amazon_avg,
    ROUND(AVG(CASE WHEN p.channel = 'amazon'    THEN p.price_usd END)
        - AVG(CASE WHEN p.channel = 'own_site'  THEN p.price_usd END), 2)         AS gap_amazon_minus_own
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
GROUP BY b.name
HAVING own_site_avg IS NOT NULL AND amazon_avg IS NOT NULL
ORDER BY gap_amazon_minus_own DESC;


-- Q9: Subscription discount depth — single vs sub price per brand
SELECT
    b.name                                                                                          AS brand,
    ROUND(AVG(CASE WHEN p.purchase_type = 'single'       THEN p.price_usd END), 2)                AS single_avg,
    ROUND(AVG(CASE WHEN p.purchase_type = 'subscription' THEN p.price_usd END), 2)                AS sub_avg,
    ROUND(100.0 * (1 -
        AVG(CASE WHEN p.purchase_type = 'subscription' THEN p.price_usd END) /
        AVG(CASE WHEN p.purchase_type = 'single'       THEN p.price_usd END)
    ), 1)                                                                                           AS sub_discount_pct
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
GROUP BY b.name
HAVING single_avg IS NOT NULL AND sub_avg IS NOT NULL
ORDER BY sub_discount_pct DESC;


-- Q10: Total SKU count per brand (catalog breadth)
SELECT
    b.name                          AS brand,
    COUNT(DISTINCT pr.id)           AS product_count,
    COUNT(DISTINCT p.id)            AS price_row_count
FROM products pr
JOIN brands b    ON b.id  = pr.brand_id
LEFT JOIN prices p ON p.product_id = pr.id
GROUP BY b.name
ORDER BY product_count DESC;
