-- 03_queries.sql — Competitive analysis queries for HabitONE
-- All queries are standalone and can be run in any order.
-- Assumes db/competitors.db was generated by 02_load_db.py.


-- Q1: Average price per gram by brand (full listed price, no discount applied)
SELECT
    b.name                                        AS brand,
    ROUND(AVG(p.price_usd / p.volume_g), 4)      AS avg_price_per_g,
    COUNT(*)                                       AS sku_count
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
GROUP BY b.name
ORDER BY avg_price_per_g;


-- Q2: Effective price per gram after applying discounts
SELECT
    b.name                                                                      AS brand,
    ROUND(AVG(p.price_usd * (1 - p.discount_pct / 100.0) / p.volume_g), 4)   AS effective_price_per_g
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
GROUP BY b.name
ORDER BY effective_price_per_g;


-- Q3: Where does HabitONE sit in the market price distribution?
WITH brand_avg AS (
    SELECT
        b.name,
        b.is_habitone,
        AVG(p.price_usd / p.volume_g) AS avg_ppg
    FROM prices p
    JOIN products pr ON pr.id = p.product_id
    JOIN brands b    ON b.id  = pr.brand_id
    WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
    GROUP BY b.name, b.is_habitone
),
ranked AS (
    SELECT
        name,
        is_habitone,
        ROUND(avg_ppg, 4) AS avg_ppg,
        ROUND(
            100.0 * (ROW_NUMBER() OVER (ORDER BY avg_ppg) - 1)
            / (COUNT(*) OVER () - 1),
            1
        ) AS pct_rank
    FROM brand_avg
)
SELECT * FROM ranked ORDER BY avg_ppg;


-- Q4: Share of SKUs with active discounts per brand
SELECT
    b.name                                                                                      AS brand,
    COUNT(*)                                                                                    AS total_skus,
    SUM(CASE WHEN p.discount_pct > 0 THEN 1 ELSE 0 END)                                        AS discounted_skus,
    ROUND(100.0 * SUM(CASE WHEN p.discount_pct > 0 THEN 1 ELSE 0 END) / COUNT(*), 1)           AS discount_coverage_pct
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
GROUP BY b.name
ORDER BY discount_coverage_pct DESC;


-- Q5: SKU count by brand and format — shows catalog depth and gaps
SELECT
    b.name       AS brand,
    pr.format,
    COUNT(*)     AS sku_count
FROM products pr
JOIN brands b ON b.id = pr.brand_id
GROUP BY b.name, pr.format
ORDER BY b.name, sku_count DESC;


-- Q6: Formats competitors offer that HabitONE does not
SELECT DISTINCT pr.format
FROM products pr
JOIN brands b ON b.id = pr.brand_id
WHERE b.is_habitone = 0
  AND pr.format NOT IN (
      SELECT DISTINCT pr2.format
      FROM products pr2
      JOIN brands b2 ON b2.id = pr2.brand_id
      WHERE b2.is_habitone = 1
  )
  AND pr.format IS NOT NULL
ORDER BY pr.format;


-- Q7 (bonus): Price spread within each format — useful for positioning
SELECT
    pr.format,
    COUNT(*)                                        AS sku_count,
    ROUND(MIN(p.price_usd / p.volume_g), 4)        AS min_ppg,
    ROUND(AVG(p.price_usd / p.volume_g), 4)        AS avg_ppg,
    ROUND(MAX(p.price_usd / p.volume_g), 4)        AS max_ppg
FROM prices p
JOIN products pr ON pr.id = p.product_id
WHERE p.volume_g IS NOT NULL AND p.volume_g > 0
GROUP BY pr.format
ORDER BY avg_ppg DESC;


-- Q8 (bonus): Channel coverage — how many brands have eBay presence vs own-site only
SELECT
    p.channel,
    COUNT(DISTINCT b.id)  AS brand_count,
    COUNT(*)              AS total_price_records
FROM prices p
JOIN products pr ON pr.id = p.product_id
JOIN brands b    ON b.id  = pr.brand_id
GROUP BY p.channel
ORDER BY brand_count DESC;
